test.url=http://localhost:8080

#????
login.uri=/login

#????????
getUserInfo.uri=/getUserInfo

#????????
updateUserInfo.uri=/updateUserInfo

#????????
getUserList.uri=/getUserList

#??????
addUser.uri=/addUser